name: Training pipeline

on:
  push:
    branches:
      - train

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install training deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn torch mlflow

      - name: Ensure notebooks are stripped
        shell: bash -l {0}
        run: |
          python -m pip install nbstripout
          nbstripout --check experiments/**/*.ipynb

      - name: Run training
        run: |
          echo "Run model training here"